import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import BookFlight from '../components/BookFlight'
import LeftHeader from '../components/LeftHeader'
import TopHeader from '../components/TopHeader'
import skyImage from '../public/sky4.png'
import planeImage from '../public/plane.png'
import SpecialOffers from '../components/SpecialOffers'
import BestOffer from '../components/BestOffer'
import Banner from '../components/Banner'

const Home: NextPage = () => {
  return (
    <div className='bg-[#EBF0F3] text-white h-screen w-screen overflow-y-scroll
    z-0 overflow-x-hidden scrollbar-thin md:scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#288bc4]/80 relative'>
      <Head>
        <title>KarimBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Head Section */}
      <div className='h-96 bg-[#1a507c] relative '>
        {/* Background Image */}

        {/* Sky image */}
        <div className='w-full h-5'>
          <div className='w-full h-[500px] absolute bottom-5'>
            <Image
              src={skyImage}
              alt='Sky'
              layout='responsive'
              objectFit='cover'
            />
          </div>
        </div>

        {/* Plane Image */}
        <div>
          <div className='absolute right-44 top-44'>
            <Image
              src={planeImage}
              alt='Sky'
              width={162.72}
              height={53.42}
            />
          </div>
        </div>

        {/* Top Header*/}
        <TopHeader />

        {/* Left Header */}
        <LeftHeader
          home={true}
          wallet={false}
          booking={false}
          business={false}
          explore={false}
          support={false}
        />

      </div >

      {/* Middle Section */}
      <section className='h-screen w-full absolute top-16 left-0 z-20 space-y-20'>
        <BookFlight />
        <SpecialOffers />
        <BestOffer />
        <Banner />
        {/* To make a space in the last section */}
        <div className='h-[1px]'>
        </div>
      </section>
    </div>
  )
}

export default Home


// import React, { Suspense } from 'react';

// const OtherComponent = React.lazy(() => import('./OtherComponent'));

/* 
<Suspense fallback={<div>Loading...</div>}>
        <OtherComponent />
      </Suspense> 
*/