import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import BookFlight from '../components/BookFlight'
import LeftHeader from '../components/LeftHeader'
import TopHeader from '../components/TopHeader'
import skyImage from '../public/sky4.png'
import planeImage from '../public/plane.png'

const Home: NextPage = () => {
  return (
    <div className='bg-[#EBF0F3]'>
      <Head>
        <title>KarimBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Head Section */}
      <section className='h-screen'>
        <div className='h-96 bg-[#1a507c] relative'>
          {/* Background Image */}

          {/* Sky image */}
          <div className='w-full h-5'>
            <div className='w-full h-[500px] absolute bottom-28'>
              <Image
                src={skyImage}
                alt='Sky'
                layout='responsive'
                objectFit='cover'
              />
            </div>
          </div>

          {/* Plane Image */}
          <div>
            <div className='absolute right-44 top-32'>
              <Image
                src={planeImage}
                alt='Sky'
                width={162.72}
                height={53.42}
              />
            </div>
          </div>

          {/* Top Header*/}
          <TopHeader />

          {/* Left Header */}
          <LeftHeader
            home={true}
            wallet={false}
            booking={false}
            business={false}
            explore={false}
            support={false}
          />

          {/* Book Flight */}
          <BookFlight />
        </div >
      </section>

      {/* TODO: Offers Section */}
      <section className='h-screen'>
        <h1>hi</h1>
        <h1>hi</h1>
        <h1>hi</h1>
      </section>
    </div>
  )
}

export default Home


// import React, { Suspense } from 'react';

// const OtherComponent = React.lazy(() => import('./OtherComponent'));

/* 
<Suspense fallback={<div>Loading...</div>}>
        <OtherComponent />
      </Suspense> 
*/