import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Karim Booking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header including The section at left*/}

      {/* Search section */}

    </div>
  )
}

export default Home


// import React, { Suspense } from 'react';

// const OtherComponent = React.lazy(() => import('./OtherComponent'));

/* 
<Suspense fallback={<div>Loading...</div>}>
        <OtherComponent />
      </Suspense> 
*/