/* eslint-disable react-hooks/rules-of-hooks */
import Head from 'next/head'
import Image from 'next/image'
import React, { Suspense, useState } from 'react'
import TopHeader from '../components/indexComponents/TopHeader'
import skyImage from '../public/sky4.png'
import planeImage from '../public/plane.png'
import { AdjustmentsHorizontalIcon, BellAlertIcon, CreditCardIcon, LockClosedIcon, UserPlusIcon, UsersIcon } from '@heroicons/react/24/outline'
import LeftHeader from '../components/indexComponents/LeftHeader'
import { useRouter } from 'next/router'
import LoadingSpinner from '../components/indexComponents/LoadingSpinner'
type Props = {}

const settings = (props: Props) => {
    const router = useRouter()
    const PersonalDetails = React.lazy(() => import('../components/settingsComponents/PersonalDetails'));
    const Preferences = React.lazy(() => import('../components/settingsComponents/Preferences'));

    const [personal, setPersonal] = useState(true)
    const [preferences, setPreferences] = useState(false)

    return (
        <div className='bg-white text-white h-screen w-screen overflow-y-scroll
            z-0 overflow-x-hidden scrollbar-thin scrollbar-track-gray-400/20 scrollbar-thumb-[#288bc4]/80 relative'>
            <Head>
                <title>KarimBook</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* Head Section */}
            <div className='h-16 bg-[#1a507c] relative '>
                {/* Background Image */}

                {/* Sky image */}
                <div className='w-full h-5'>
                    <div className='w-full h-16 absolute'>
                        <Image
                            src={skyImage}
                            alt='Sky'
                            layout='fill'
                            objectFit='cover'
                        />
                    </div>
                </div>
                <h3
                    className='absolute top-4 left-60 font-fasthand font-semibold text-white text-xl -rotate-6 cursor-pointer'
                    onClick={() => {
                        router.push({
                            pathname: '/'
                        })
                    }}
                >KarimBook</h3>

                {/* Top Header*/}
                <TopHeader />
            </div >
            {/* Left Header */}
            {/* TODO: make all of setting like the first 2 */}
            <div className='max-w-6xl mx-auto grid grid-cols-4 my-4'>
                <div className='border border-gray-300 rounded-lg'>
                    {/* Personal details */}
                    <div className='p-5 border-b border-gray-300 flex items-center space-x-5 group cursor-pointer' onClick={() => {
                        setPersonal(true)
                        setPreferences(false)
                    }}>
                        <UserPlusIcon
                            className={personal ? 'h-9 w-9 text-blue-500 border border-gray-100 p-2 bg-gray-200 rounded-full' : 'h-9 w-9 group-hover:text-blue-500 text-gray-800 border border-gray-100 p-2 bg-gray-200 rounded-full'}
                        />
                        <h1 className={personal ? 'text-base text-blue-500 group-hover:underline' : 'text-base group-hover:text-blue-500 text-gray-800 group-hover:underline'}>Personal details</h1>
                    </div>
                    {/* Prefernces */}
                    <div className='p-5 border-b border-gray-300 flex items-center space-x-5 group cursor-pointer' onClick={() => {
                        setPreferences(true)
                        setPersonal(false)
                    }}>
                        <AdjustmentsHorizontalIcon
                            className={preferences ? 'h-9 w-9 text-blue-500 border border-gray-100 p-2 bg-gray-200 rounded-full' : 'h-9 w-9 group-hover:text-blue-500 text-gray-800 border border-gray-100 p-2 bg-gray-200 rounded-full'}
                        />
                        <h1 className={preferences ? 'text-base text-blue-500 group-hover:underline' : 'text-base group-hover:text-blue-500 text-gray-800 group-hover:underline'}>Personal details</h1>
                    </div>
                    {/* Security */}
                    <div className='p-5 border-b border-gray-300 flex items-center space-x-5 group cursor-pointer'>
                        <LockClosedIcon
                            className='h-9 w-9 group-hover:text-blue-500 text-gray-800 border border-gray-100 p-2 bg-gray-200 rounded-full'
                        />
                        <h1 className='text-base group-hover:text-blue-500 text-gray-800 group-hover:underline'>Security</h1>
                    </div>
                    {/* Payment details */}
                    <div className='p-5 border-b border-gray-300 flex items-center space-x-5 group cursor-pointer'>
                        <CreditCardIcon
                            className='h-9 w-9 group-hover:text-blue-500 text-gray-800 border border-gray-100 p-2 bg-gray-200 rounded-full'
                        />
                        <h1 className='text-base group-hover:text-blue-500 text-gray-800 group-hover:underline'>Payment details</h1>
                    </div>
                    {/* Email notification */}
                    <div className='p-5 border-b border-gray-300 flex items-center space-x-5 group cursor-pointer'>
                        <BellAlertIcon
                            className='h-9 w-9 group-hover:text-blue-500 text-gray-800 border border-gray-100 p-2 bg-gray-200 rounded-full'
                        />
                        <h1 className='text-base group-hover:text-blue-500 text-gray-800 group-hover:underline'>Email notification</h1>
                    </div>
                    {/* Other travellers */}
                    <div className='p-5 border-b border-gray-300 flex items-center space-x-5 group cursor-pointer'>
                        <UsersIcon
                            className='h-9 w-9 group-hover:text-blue-500 text-gray-800 border border-gray-100 p-2 bg-gray-200 rounded-full'
                        />
                        <h1 className='text-base group-hover:text-blue-500 text-gray-800 group-hover:underline'>Other travellers</h1>
                    </div>
                </div>
                <div className='col-span-3'>
                    {
                        personal && (
                            <Suspense fallback={<LoadingSpinner />}>
                                <PersonalDetails />
                            </Suspense>
                        )
                    }
                    {
                        preferences && (
                            <Suspense fallback={<LoadingSpinner />}>
                                <Preferences />
                            </Suspense>
                        )
                    }
                </div>
            </div>
        </div>
    )
}

export default settings